let constants = {
  // Labels
  aboutUs: "About Us",
  companyDetails:
    "This company started in 10-January-2018 in Agra.And Our target to grow the strength & growth of our company.so that we can share the knowledge all over in India.And Help Our Inspirants to achieve their goal and creack the competative & government exam",
  changePassword: "Change Password",
  change: "Change",
  cancel: "Cancel",
  htmlTutorial: "HTML Tutorial",
  cssTutorial: "CSS Tutorial",
  jsTutorial: "JAVASCRIPT Tutorial",
  angularTutorial: "ANGULAR Tutorial",
  reactTutorial: "REACT Tutorial",
  htmlText: "In this Tutorial, you can learn top-wise about HTML.",
  cssText: "In this Tutorial, you can learn top-wise about CSS.",
  jsText: "In this Tutorial, you can learn top-wise about JAVASCRIPT.",
  angularText: "In this Tutorial, you can learn top-wise about ANGULAR.",
  reactText: "In this Tutorial, you can learn top-wise about REACT.",
  htmlOnlineTest: "HTML Online Test",
  cssOnlineTest: "CSS Online Test",
  jsOnlineTest: "JAVASCRIPT Online Test",
  angularOnlineTest: "ANGULAR Online Test",
  reactOnlineTest: "REACT Online Test",
  htmlOnlineText: "By doing this online test,You can test your HTML skill.",
  cssOnlineText: "By doing this online test,You can test your CSS skill.",
  jsOnlineText: "By doing this online test,You can test your JAVASCRIPT skill.",
  angularOnlineText:
    "By doing this online test,You can test your ANGULAR skill.",
  reactOnlineText: "By doing this online test,You can test your REACT skill.",
  ourCourses: "Our Courses",
  ourServices: "Our Services",
  customersDetails: "Customers Details",
  updateCustomerDetails: "Update Customer Details",
  programmerTechnoFunn: "Programmer TechnoFunn",
  home: "Home",
  services: "Services",
  Career: "Career",
  contactUs: "Contact Us",
  jobOpenings: "Job Openings",
  createJobOpening: "Create Job Opening",
  listofJobOpenings: "List of Job Openings",
  addJobOpenings: "Add Job Openings",
  selectTheSkills: "Select the skills",
  selectTheQualification: "Select the qualification",
  selectTheWorkMode: "Select the work mode",
  noJobOpenings: "No job openings",
  noSavedJob: "No Saved Jobs",
  appliedJob: "Applied Jobs",
  savedJob: "Saved Jobs",
  signIn: "Sign In",
  profile: "Profile",
  jobOpeningList: "Job Opening List",
  onlineTestMaterial: "Online Test Material",
  login: "Login",
  onlineTest: "Online Test",
  selectALevel: "Select a level",
  selectAnOption: "Select an option",
  selectAccount: "Select an Account Type",
  basic: "Basic",
  advanced: "Advanced",
  intermediate: "Intermediate",
  certificateOfCompletion: "Certificate Of Completion",
  authorisedSignatory: "Authorised Signatory",
  addQuestions: "Add Questions",
  listOfQuestions: "List of Questions",
  addQUESTIONS: "ADD QUESTIONS",
  selectAnCourse: "Select an Course",
  noDataAvailable: "No data available",
  html: "HTML",
  css: "CSS",
  js: "JAVASCRIPT",
  angular: "ANGULAR",
  react: "REACT",
  php: "PHP",
  updateProfile: "Update Profile",
  ourPurpose: "Our Purpose",
  student: "Student",
  business: "Business",
  admin: "Admin",
  employer: "Employer",
  recruiter: "Recruiter",
  beginner: "Beginner",
  experienced: "Experienced",
  selectLevel: "Select A Level",
  purposeText:
    "To Introduce the Youth Generation with Technologies.. & Help them to crack the competative and government exam!!",
  register: "Register",
  uploadFiles: "Upload Resume",
  ourTeam: "Our Team",
  // Buttons Labels
  clickHere: "Click Here",
  update: "Update",
  create: "Create",
  search: "Search",
  remove: "Remove",
  submit: "Submit",
  reset: "Reset",
};

export default constants;
